/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as InfluencersRouteImport } from './routes/influencers'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForInfluencersRouteImport } from './routes/for-influencers'
import { Route as ForBusinessesRouteImport } from './routes/for-businesses'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as InfluencersIdRouteImport } from './routes/influencers.$id'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardMatchesRouteImport } from './routes/dashboard.matches'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencersRoute = InfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForInfluencersRoute = ForInfluencersRouteImport.update({
  id: '/for-influencers',
  path: '/for-influencers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBusinessesRoute = ForBusinessesRouteImport.update({
  id: '/for-businesses',
  path: '/for-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const InfluencersIdRoute = InfluencersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InfluencersRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMatchesRoute = DashboardMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-influencers': typeof ForInfluencersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/influencers': typeof InfluencersRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/influencers/$id': typeof InfluencersIdRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-influencers': typeof ForInfluencersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/influencers': typeof InfluencersRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/influencers/$id': typeof InfluencersIdRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/for-businesses': typeof ForBusinessesRoute
  '/for-influencers': typeof ForInfluencersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/influencers': typeof InfluencersRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/influencers/$id': typeof InfluencersIdRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/for-businesses'
    | '/for-influencers'
    | '/how-it-works'
    | '/influencers'
    | '/listings'
    | '/pricing'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/analytics'
    | '/dashboard/matches'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/influencers/$id'
    | '/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/for-businesses'
    | '/for-influencers'
    | '/how-it-works'
    | '/influencers'
    | '/listings'
    | '/pricing'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/analytics'
    | '/dashboard/matches'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/influencers/$id'
    | '/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/for-businesses'
    | '/for-influencers'
    | '/how-it-works'
    | '/influencers'
    | '/listings'
    | '/pricing'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/analytics'
    | '/dashboard/matches'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/influencers/$id'
    | '/listings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  ForBusinessesRoute: typeof ForBusinessesRoute
  ForInfluencersRoute: typeof ForInfluencersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InfluencersRoute: typeof InfluencersRouteWithChildren
  ListingsRoute: typeof ListingsRouteWithChildren
  PricingRoute: typeof PricingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers': {
      id: '/influencers'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof InfluencersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-influencers': {
      id: '/for-influencers'
      path: '/for-influencers'
      fullPath: '/for-influencers'
      preLoaderRoute: typeof ForInfluencersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-businesses': {
      id: '/for-businesses'
      path: '/for-businesses'
      fullPath: '/for-businesses'
      preLoaderRoute: typeof ForBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/influencers/$id': {
      id: '/influencers/$id'
      path: '/$id'
      fullPath: '/influencers/$id'
      preLoaderRoute: typeof InfluencersIdRouteImport
      parentRoute: typeof InfluencersRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/matches': {
      id: '/dashboard/matches'
      path: '/matches'
      fullPath: '/dashboard/matches'
      preLoaderRoute: typeof DashboardMatchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardMatchesRoute: typeof DashboardMatchesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardMatchesRoute: DashboardMatchesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface InfluencersRouteChildren {
  InfluencersIdRoute: typeof InfluencersIdRoute
}

const InfluencersRouteChildren: InfluencersRouteChildren = {
  InfluencersIdRoute: InfluencersIdRoute,
}

const InfluencersRouteWithChildren = InfluencersRoute._addFileChildren(
  InfluencersRouteChildren,
)

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  ForBusinessesRoute: ForBusinessesRoute,
  ForInfluencersRoute: ForInfluencersRoute,
  HowItWorksRoute: HowItWorksRoute,
  InfluencersRoute: InfluencersRouteWithChildren,
  ListingsRoute: ListingsRouteWithChildren,
  PricingRoute: PricingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
